# Generated by Django 4.1.3 on 2023-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_is_rgpd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
