# Generated by Django 3.1.14 on 2023-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank='True', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mail_visible',
            field=models.BooleanField(default=False),
        ),
    ]
