# Generated by Django 3.1.14 on 2023-11-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231115_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_name_visible',
            field=models.BooleanField(default=False),
        ),
    ]
