# Generated by Django 3.1.14 on 2023-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231122_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_color',
            field=models.CharField(default='#ec6a52', max_length=255),
        ),
    ]
