# Generated by Django 3.1.14 on 2023-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231122_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_color',
            field=models.CharField(default='#ec6a52', max_length=255, null=True),
        ),
    ]
